### ISSUE TITLE
white bar on first-load screen

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#32]
![Image from iOS (3)](https://user-images.githubusercontent.com/11731079/55011500-f59da380-4fb3-11e9-960d-2ea00dfaec75.png)

**Comment by frizman21** [comment]
@conrad-vanl regardless of resolution of the image, would it make more since to stretch whatever image into the space provided? all iPhones/Androids are created equal, yeah?

**Comment by frizman21** [comment]
Waiting on Becca for full scale images.

**Comment by mikezigster** [comment]
@conrad-vanl Here are the revised files:  https://www.dropbox.com/sh/53iiy7j0e420vlo/AAAEeXZc8DCNby7xQCUpxRNUa?dl=0

**Comment by frizman21** [comment]
![CLC19 App WelcomeScreens 1125x2436px Plum RJ](https://user-images.githubusercontent.com/11731079/55081759-728d5380-506e-11e9-9b6d-1258f99999ef.png)
![CLC19 App WelcomeScreens 1125x2436px Orange RJ](https://user-images.githubusercontent.com/11731079/55081760-728d5380-506e-11e9-8fe8-4f32bf47646f.png)
![CLC19 App WelcomeScreens 1125x2436px Gray RJ](https://user-images.githubusercontent.com/11731079/55081761-728d5380-506e-11e9-9791-ab8db88e4ea0.png)

**Comment by conrad-vanl** [comment]
Closed in #40 and #33
