### ISSUE TITLE
Android Deployment

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#33]
- [x] styling issues.

**Comment by frizman21** [comment]
@conrad-vanl working tonight.

**Comment by conrad-vanl** [comment]
@frizman21 build is fixed and styling issues solved. It's up on appcenter and builds are succeeding there, but I still can't get into the play console. Can you resend the invite?

**Comment by frizman21** [comment]
@conrad-vanl which email?

**Comment by conrad-vanl** [comment]
This should be good to go now. Out of free build time on AppCenter. Can submit a manual build, although it's a bit of a PITA, or we can upgrade for $40 for one month and keep the automation 🚂 going.

**Comment by frizman21** [comment]
@conrad-vanl just to close this thread on github, we're now at $40 a month. We'll turn this back down after CLC.
