### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#34]
let me add y'all to onesignal
send me email addresses for accounts you'd like to have access
just added you and mike
should get emails
once logged in go to Messages > New Push
certain options may or may not work, depending on if I have it enabled / set up within the app
but not sure you'll need to mess with much of those options (you'll see what I mean when you get logged in)

**Comment by frizman21** [comment]
@conrad-vanl I don't have an email. @mikezigster, Did you get one?

**Comment by mikezigster** [comment]
Nope, I am not seeing anything in my inbox.


Michael Ziegler
Communications Coordinator
Watermark Community Church

**Comment by frizman21** [comment]
Tried to create an account in Signal - no joy, says that I have one. Tried password reset. Didn't get an email.

**Comment by frizman21** [comment]
What are our options and how do we want to use it? Test those use cases prior to CLC starting.

**Comment by conrad-vanl** [comment]
@frizman21 is there anything on this issue you currently need from me?

**Comment by mikezigster** [comment]
@conrad-vanl I don't think so.  This is on me.
