### ISSUE TITLE
User Feedback: Howell - Speaker not active link

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#44]
Development:
- [x] Speakers listed on events appear to be able to link to a bio (arrow) but no active link.

Content:
- [ ] Under "Worship" is a "Big Commitments..." Breakout.  Wrong category, not a worship focus. (See attached pic)
- [ ] Under "Recovery" there is a field formatting error (see attached pic)

**Comment by frizman21** [comment]
@mikezigster you and emili have two.

I think I knocked out the third but waiting for the cache cycle to clear.

@conrad-vanl it aware of the first.

**Comment by mikezigster** [comment]
@frizman21 I have two.  

I do not have the issue on one.  Arrows send me to speaker bio page.

**Comment by frizman21** [comment]
sorry, @mikezigster , need to add Android flag on this issue.

**Comment by conrad-vanl** [comment]
Speaker tapping is fixed in the released version on play store

**Comment by jpowell** [comment]
o.b.e. - now have a new app
