### ISSUE TITLE
setup uptimerobot for the CLC API

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#48]

**Comment by frizman21** [comment]
@conrad-vanl please provide suitable URL

**Comment by conrad-vanl** [comment]
CDN-backed (what the app uses) https://wcc-clc-api-production-herokuapp-com.global.ssl.fastly.net/graphql

Direct to heroku (what the cdn sits in front of) https://wcc-clc-api-production.herokuapp.com/graphql

**Comment by frizman21** [comment]
![image](https://user-images.githubusercontent.com/11731079/55126217-5fb06880-50da-11e9-9f2f-d289072eb75e.png)
