### ISSUE TITLE
Turn off $40/month CI bill + heroku

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#50]
after CLC, reduce cost of 
- [ ] Heroku
- [ ] App Center

**Comment by jpowell** [comment]
@frizman21 still a thing?

**Comment by frizman21** [comment]
we left it on, even though we didn't use it. Let's plan to turn off after CLC.

**Comment by jpowell** [comment]
I think this is done - @gburgett @frizman21 yes?

**Comment by gburgett** [comment]
Yes, we are down to the bare bones which runs us approx. $50/mo (1 heroku unit + $25 fastly charge)
