### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#55]
19:10-19:11 was the time slice

![image (1)](https://user-images.githubusercontent.com/11731079/55204601-a61acb80-519d-11e9-98f7-046546b5cdae.png)

![image](https://user-images.githubusercontent.com/11731079/55204602-a61acb80-519d-11e9-9e46-3a6e5f6c3d11.png)

**Comment by conrad-vanl** [comment]
Haven't been able to track or reproduce. Added logging visibility to heroku instance so if triggered again can investigate.
