### ISSUE TITLE
Add a root-level `README.md` file

### ISSUE THREAD

**Issue by conrad-vanl** [watermarkchurch/clc-conference-app#68]
Lets get some documentation!

I think we can create a real quick readme file in the root of this repo that describes how to get the project running, and I can start adding more stuff to it over time, especially how to cut releases, the contentful schema, etc. I will work on typing up a general architecture intro that explains how everything is built. That's something we need on Apollos core (the open source stuff this project is based on) anyways.

Here's the steps that should be required to get the project running on a local machine:

1. Make sure `yarn` is installed https://yarnpkg.com/en/docs/install#mac-stable
2. Create a `.env` file inside of `packages/ConferenceApp` and `packages/apollos-api`. You can copy the `.env.example` files in each and use their default values.

For `apollos-api`, you'll have to get a copy of the `.env` file from someone else, as this file contains secrets that we cannot post on github (shoot me a DM on slack and i'll send it your way).

3. From the root of the repo, run `yarn` which will install dependencies
4. Running `yarn start` from the root of the repo will spin up both the `api` layer and the `react-native` packager.

From there, you can build the native app using your tool of choice. If you prefer to use Xcode or Android Studio directly, you can open those applications and find the native project file inside of `packages/ConferenceApp/ios` and `packages/ConferenceApp/android`. You should be able to open those files, select a development team (Watermark or personal) and build and run on a simulator. 

We can also add `ios` and `android` yarn cmds that will open a simulator for you. But those don't currently exist in the repo.

**Comment by caleblawrence** [comment]
Awesome I'll try to get it all setup tonight. Thanks for the helpful steps.
