### ISSUE TITLE
CLC 2021 Wish List

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#70]
CLC 2021 Dates: 26-29 April

### Aesthetics
- updated backgrounds and textures
- update the on-board art / text.

### Problem: Be able to RSVP to stuff
- Breakouts, due to COVID, we need a better understanding of how many people are interested in that breakout in order to adjust rooms and such.
- We are running "reunions" - all the churches that run re:gen get together. This is a registration required event. The ask will be made ahead of time, but they'll want to be able to register in the app for those. Registration is not limited, but we need to know. (Zig to go ask for clarity on how important this registration is on a per person basis)
- Staff consulting at CLC. Similar to staff consulting calls. There is an existing webapp that performs this function. (A Rock workflow) Consider an iCal sort of interface that puts this appointment on their conference schedule. Also, considering the deep link on the confirmation email on this appointment that would drive people download the app.

### Problem: Digital Handouts
- Breakouts, Workshops, and Main Stage events will have digital handouts. 
- These will be preloaded prior to the conference. 
- The Information Architecture is the post conference resources. (currently in Media system)
- They will all be PDFs.
- There might be multiple PDFs per event: example being a one-page reference, a curriculum preview, and then slides.
- Consider a QR code that allows the app/phone to jump to the breakout details and the downloadable resources.
- Needs a method to send/share those resources with themselves (like via email or copy/paste a link or...)

### Problem: Enable some fun
- Random generator to pull a number between 1 and 6 - integers. Replace the die. (A group game, "anyone that rolls a three, come up on stage") 
- Random generator that pulls from a bank of farkel consequences.
- Is there a farkle app that would eliminate passing dice around?

**Comment by conrad-vanl** [comment]
@frizman21 here are paths to images that can be updated. You can post updated images in this GitHub Issue (or a separate issue) and I'll open a PR

**Updated Images**
Home Tab Logo: https://github.com/watermarkchurch/clc-conference-app/blob/master/packages/ConferenceApp/src/tabs/home/CLC-center.png

Home Tab Texture: https://github.com/watermarkchurch/clc-conference-app/blob/master/packages/ConferenceApp/src/tabs/home/texture.png

App Icon (just give me a single large square icon and I'll generate sizes if you wish to change): https://github.com/watermarkchurch/clc-conference-app/tree/master/packages/ConferenceApp/ios/ConferenceApp/Images.xcassets/AppIcon.appiconset

Splash Screen LOGO (this gets centered on the splash screen when app is booting): https://github.com/watermarkchurch/clc-conference-app/tree/master/packages/ConferenceApp/ios/ConferenceApp/Images.xcassets/SplashImage.imageset

 Splash Screen Background Texture: https://github.com/watermarkchurch/clc-conference-app/tree/master/packages/ConferenceApp/ios/ConferenceApp/Images.xcassets/SplashImage.imageset

**Comment by jpowell** [comment]
This was done with the app in 2021 no living https://github.com/watermarkchurch/clc-app-v2
